version: '3.5'

services:

  bank-account-reader:
    image: bank-account-reader:dev    
    build:
      context: .
      dockerfile: BankAccount.Reader/Dockerfile
      args:
        VERSION: 1.0.0.0  

  bank-account-writer:
    image: bank-account-writer:dev    
    build:
      context: .
      dockerfile: BankAccount.Writer/Dockerfile
      args:
        VERSION: 1.0.0.0  

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: Administrator
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ state
    networks:
      - default

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "sql,s!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql  # Persist SQL Server DB files
    networks:
      - default
  
volumes:
  rabbitmq_data:
  sqlserver_data:

networks:
   default:
     external: true
     name: shared-infrastructure-network